apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYWdyMzMzMjIxIiwicGFzc3dvcmQiOiJnaHBfalJkZEl4andTeVhwN1ZvU2VuekIxZUVhSmQ2RGM0M2RpZmdmIiwiZW1haWwiOiJhZ3IzMzMyMjFAZ21haWwuY29tIiwiYXV0aCI6IllXZHlNek16TWpJeE9tZG9jRjlxVW1Sa1NYaHFkMU41V0hBM1ZtOVRaVzU2UWpGbFJXRktaRFpFWXpRelpHbG1aMlk9In19fQ==
type: kubernetes.io/dockerconfigjson
